CREATE USER pcapagent LOGIN ENCRYPTED PASSWORD 'REPLACEONINSTALL';
GRANT pg_read_server_files TO pcapagent;
CREATE USER selectuser LOGIN ENCRYPTED PASSWORD 'REPLACEONINSTALL';
CREATE USER pcapanalyzer LOGIN CREATEDB ENCRYPTED PASSWORD 'REPLACEONINSTALL';
CREATE USER pcapuserchecker LOGIN CREATEDB ENCRYPTED PASSWORD 'REPLACEONINSTALL';
GRANT pg_read_server_files TO pcapanalyzer;
GRANT pg_signal_backend TO pcapanalyzer;
SET ROLE pcapanalyzer;
